In [1]:
from datasets import load_dataset
dataset = load_dataset("emotion")

/usr/local/lib/python3.12/dist-packages/huggingface_hub/utils/_auth.py:94: UserWarning:
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(

README.md: 0.00B [00:00, ?B/s]

split/train-00000-of-00001.parquet:   0%|          | 0.00/1.03M [00:00<?, ?B/s]

split/validation-00000-of-00001.parquet:   0%|          | 0.00/127k [00:00<?, ?B/s]

split/test-00000-of-00001.parquet:   0%|          | 0.00/129k [00:00<?, ?B/s]

Generating train split:   0%|          | 0/16000 [00:00<?, ? examples/s]

Generating validation split:   0%|          | 0/2000 [00:00<?, ? examples/s]

Generating test split:   0%|          | 0/2000 [00:00<?, ? examples/s]

In [3]:
import pandas as pd
df = pd.DataFrame(dataset['train'])
df.to_csv("emotion_dataset.csv", index=False)

In [4]:

df.head()

                                                text  label
0                            i didnt feel humiliated      0
1  i can go from feeling so hopeless to so damned...      0
2   im grabbing a minute to post i feel greedy wrong      3
3  i am ever feeling nostalgic about the fireplac...      2
4                               i am feeling grouchy      3

In [5]:
df['label'].value_counts()

label
1    5362
0    4666
3    2159
4    1937
2    1304
5     572
Name: count, dtype: int64

In [6]:
for label in df['label'].unique():
    print(f"\nLabel {label} examples:")
    print(df[df['label'] == label]['text'].head(3))

Label 0 examples:
0                              i didnt feel humiliated
1    i can go from feeling so hopeless to so damned...
5    ive been feeling a little burdened lately wasn...
Name: text, dtype: object

Label 3 examples:
2      im grabbing a minute to post i feel greedy wrong
4                                  i am feeling grouchy
12    i think it s the easiest time of year to feel ...
Name: text, dtype: object

Label 2 examples:
3     i am ever feeling nostalgic about the fireplac...
9                                   i feel romantic too
47    i can t let go of that sad feeling that i want...
Name: text, dtype: object

Label 5 examples:
6     ive been taking or milligrams or times recomme...
32    i have seen heard and read over the past coupl...
57    i keep feeling pleasantly surprised at his sup...
Name: text, dtype: object

Label 4 examples:
7     i feel as confused about life as a teenager or...
19    i now feel compromised and skeptical of the va...
21    i am feeling completely overwhelmed i have two...
Name: text, dtype: object

Label 1 examples:
8     i have been with petronas for years i feel tha...
11    i do feel that running is a divine experience ...
14    i have immense sympathy with the general point...
Name: text, dtype: object

In [7]:
label_map = {
    0: "Sad 😢",
    1: "Happy 😄",
    2: "Love 💖",
    3: "Angry 😡",
    4: "Fear 😨",
    5: "Surprise 😲"
}

In [40]:
import pandas as pd
import joblib
from sklearn.pipeline import Pipeline
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.naive_bayes import MultinomialNB

In [41]:
# Build pipeline
pipeline = Pipeline([
    ("tfidf", TfidfVectorizer()),
    ("clf", MultinomialNB())
])

In [42]:
# FIT (THIS IS CRITICAL)
pipeline.fit(df["text"], df["label"])

Pipeline(steps=[('tfidf', TfidfVectorizer()), ('clf', MultinomialNB())])

In [46]:
# HARD CHECK
print("TF-IDF fitted?", hasattr(pipeline.named_steps["tfidf"], "idf_"))

TF-IDF fitted? True

In [47]:
joblib.dump(pipeline, "sentiment_model.pkl")

['sentiment_model.pkl']

In [17]:
def predict_emotion(sentence):
    pred_label = model.predict([sentence])[0]
    return label_map[pred_label]

In [18]:
predict_emotion("I feel so lonely and broken")

'Sad 😢'

In [28]:
predict_emotion("i'm feeling confused about my future")

'Fear 😨'

In [29]:
predict_emotion("today is just wow")

'Happy 😄'

In [30]:
predict_emotion("i dont like him")

'Sad 😢'

In [45]:
y_pred = model.predict(X_test)
accuracy = accuracy_score(y_test, y_pred)

print("Accuracy:", accuracy)

Accuracy: 0.6175

In [48]:
import sklearn
print(sklearn.__version__)

1.6.1